"""Create access permission table

Revision ID: 41a603e5c107
Revises: b27261c8fe0f
Create Date: 2023-09-02 22:35:56.346724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41a603e5c107"
down_revision: Union[str, None] = "b27261c8fe0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesspermissions",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_unique_action_for_token",
        "accesspermissions",
        ["token", "action"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unique_action_for_token", table_name="accesspermissions")
    op.drop_table("accesspermissions")
    # ### end Alembic commands ###
